sudo: required
services:
  - docker

before_install:
  - docker build -f -t solymantaherian/docker-react Dockerfile.dev .

script:
  - docker run solymantaherian/docker-react npm run test -- --coverage