sudo: required
services:
  - docker

before_install:
  - docker build -t solymantaherian/docker-react -f Dockerfile.dev .

script:
  - docker run solymantaherian/docker-react npm run test -- --coverage